component: http
name: openai-proxy
inputs:
  src:
    src: ./
    exclude:
      - .env
  # 指定 SCF 类型为 Web 类型
  type: web
  name: openai-proxy # 填入您的函数名称
  region: na-siliconvalley
  runtime: Nodejs16.13
  memorySize: 512 # 内存大小，为保证性能，web 函数请配置 512 MB 及以上
  events: 
    - apigw: 
        parameters: 
          protocols: 
            - http
            - https
          environment: release
          endpoints: 
            - path: /
              method: ANY
app: openai-proxy-cfce484b
